### PR TITLE
Change addressbook instance to tutorbuddy

### PR DESCRIPTION
**Pull request by chwoozy**
Added `preferences.json` to `.gitignore`.

Changed addressbook instance to tutorbuddy.

### CODE REVIEW

**Review by JonahhGohh — APPROVED** [review]
LGTM
image

**Review by samleewy — CHANGES_REQUESTED** [review]
I think you'll have to make changes to `model/UserPrefs.java` as well. Doesn't seem to create `tutorbuddy.json` on isolated launch with these changes.

^ With the above changes, we'll probably not need to exclude `preferences.json` from gitignore.

**Comment by chwoozy** [comment]
> I think you'll have to make changes to `model/UserPrefs.java` as well. Doesn't seem to create `tutorbuddy.json` on isolated launch with these changes.
> 
> ^ With the above changes, we'll probably not need to exclude `preferences.json` from gitignore.

Woo thanks!

**Review by samleewy — APPROVED** [review]
works as intended after the changes!

**Pull request merged**
