### PR TITLE
Update site wide settings

### PR DESCRIPTION
**Pull request by JonahhGohh**
Change title only.
All templates are kept the same.

### CODE REVIEW

**Review by enhao25 — COMMENTED** [review]
LGTM

**Review by enhao25 — COMMENTED** [review]
LGTM, but actually what is the tutorbuddy.png which is an empty file?

**Comment by JonahhGohh** [comment]
Removed. I was actually intending to replace the github logo, but the github logo makes more sense in this case.

**Review by enhao25 — APPROVED** [review]
Noted!

**Pull request merged**
