### PR TITLE
Include some sample session when a user first starts the app

### PR DESCRIPTION
**Pull request by enhao25**
Hopefully can merge by friday 10.00am, so that can be used for the PE testing.

### CODE REVIEW

**Review by JonahhGohh — COMMENTED** [review]
Thanks for adding this!
A slight issue is that I was thinking of using this populated data to be UI images shown in the UG. 
image
I think it would be better to show some Individual sessions here instead of all recurring session?

**Comment by enhao25** [comment]
> Thanks for adding this!
> A slight issue is that I was thinking of using this populated data to be UI images shown in the UG.
> image
> I think it would be better to show some Individual sessions here instead of all recurring session?

Haha ok! Actually david li has 1 individual session. I have updated one of Bernice's recurring session to session instead. See if its ok now.

**Review by JonahhGohh — APPROVED** [review]
Thanks for changing! Ya I saw the David Li session, its just that I thought it be nice to show the UI on the UG with both the Individual and Recurring session since we planning to use the populated data for the screenshots in the UG.

LGTM!

**Review by nowknowing — COMMENTED** [review]
LGTM

**Pull request merged**
